---
- name: Fetch pre-compiled binary for "Linux x64" build of Firefox Nightly
  get_url:
    url: "{{firefox_download_url}}"
    dest: "{{download_dir}}/{{firefox_download_url | basename}}"

- name: Unpack Firefox Nightly
  unarchive:
    src: "{{download_dir}}/{{firefox_download_url | basename}}"
    dest: "{{tools_dir}}"
    creates: "{{tools_dir}}/firefox"

- name: Install Firefox Nightly
  file:
    src: "{{tools_dir}}/firefox/firefox"
    dest: /usr/bin/firefox-nightly
    state: link
  become: true
